# Generated by Django 4.2.3 on 2023-07-21 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_rename_email_from_contactus_email_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='message',
            new_name='body',
        ),
    ]
