# Generated by Django 4.2.3 on 2023-07-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_rename_message_contactus_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('path', models.CharField(max_length=255)),
                ('response_time', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
